### ISSUE TITLE
Is it compatible with GNU GPLv2+ license?

### ISSUE THREAD

**Issue by ghost** [levork/l2rib#2]
Licensing info inside `l2rib.C` is not clear.

Is it possible merge `l2rib.C` code into other FOSS software under the terms of GNU GPLv2+ license?

For example, is it possible bundle `l2rib.C` into *LeoCAD*?

- https://github.com/leozide/leocad
  - https://github.com/leozide/leocad/tree/master/docs
    - https://github.com/leozide/leocad/blob/master/docs/COPYING.txt

**Comment by levork** [comment]
Most of the license is just the MIT license.

There are three lines referring to the RenderMan interface - this relates to Pixar's copyright, a copy of which can be found here.

http://www.hradec.com/ebooks/CGI/RPS_13.5/prman_technical_rendering/users_guide/RISpec-html/copyright.html

**Comment by ghost** [comment]
So, is it compatible with *LeoCAD* licensing or not?

**Comment by levork** [comment]
The MIT license is compatible. Any programs that wish to comply with Pixar's copyright on the RenderMan interface must include the notice above.
